### ISSUE TITLE
Add progress indicator

### ISSUE THREAD

**Issue by RemoveIt** [TibiaJS/sprites-extractor#8]
Reference:
* [node-progress](https://github.com/tj/node-progress)

**Comment by RemoveIt** [comment]
I assume that you  agree with this idea

**Comment by gpedro** [comment]
Done (:

Thanks for suggesting

**Comment by RemoveIt** [comment]
:cry:  I wanted to do this

also there is no need to preserving ```out``` folder in repo when 
 ```if(!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir);
}```

**Comment by gpedro** [comment]
true. i'll remove `out` folder.
